Adjust performance expectations 
Slide the whole window ( also fixes overlay AB issues ) . 
Add the checkstyle rule FinalClass 
Add precondition to throw more informative exception when calling request ( ) before start ( ) has been called . 
Fix failing test case 
decrease default cache size to prevent OOEMs 
Made field private 
ignore eclipse project files 
HHH - 5376 Tests contain invalid SQL 
make mesh static by default 
Help topic specified . 
Add Google - internal memory consumption tests for all top - level Multiset implementations . 
removed unused import 
enable cleaner hack , so it consumes less disk space 
update generated Order class 
Fix JavaDoc . 
Peek the left overlay drawer . 
Set INHERIT_LOG4J default to false . 
help id ( IDEA - 137826 ) 
Set unsubscribed true 
Add solution to problem 78 
corrected check for duplicated classes 
GraphServiceBeanImpl always returns the same graph , even with routerId 
Added call to HystrixPlugins . reset ( ) in HystrixCommandTestWithCustomConcurrencyStrategy 
ignore failing test 
remove unused import 
Cannot edit watch in Flex debugger . 
BubbleFlowDraggable handles the onDestroyBubble ( ) . 
Eliminate an unnecessary initializer 
Hiding DrawerLayout does not fire correct accessibility event . 
missing import 
Add missing URI import 
Fix bug where SslHandler returned wrong value for getCloseNotifyTimeoutMillis ( ) 
made class final 
Use the write listener to decide between a blocking and a non blocking flush on close . 
Fix sync tests failure . 
fixed wrong UnreachedBarColor # 25 
LPS - 52171 NewEnvTestRule . RunInNewClassLoaderStatement should reset MethodCache after run , to release references to the new classloader , so that it can be gced properly 
Fix Issue # 550 
Fix cleaning scan result cache 
When configuring mmapfs it is not used since 0 . 19 . 7 , closes # 2253 . 
Fix for declaration resolve 
Fix a typo in a javadoc comment 
added a private constuctor for ticket # TACHYON - 1243 
Reading / writing the mappings - - - tested version . 
Fix typo in exception . 
Rename carrier config constant . 
Fix NPE if there is no accelerometer . 
fixed missing import 
Ensure only a single scroller animation callback per frame . 
Fixed Nullable / NotNull annotations . 
Fix a silly bug 
Set READ_REQUIRES_WRITE when initiating a handshake 
Make go case sensitive language 
Removed println 
Remove unneed clear in constructor . 
Fix HttpProxy . 
Fix server launching . 
Closes # 2786 , PixmapPacker # updateTextureAtlas returned prematurely . 
LPS - 49294 Fix compile error 
help ID ( PY - 4115 ) 
memory leak fixed ( IDEADEV - 15230 ) 
Do not return a super type if a class represents an interface . 
Make the default folder name size in the folder list the same as the default account name size in the account list 
Fix indents 
Reverted var name change . 
test refactored cont 
Remove erroneous JavaDoc 
Fix AppCompatCheckedTextView tinting compound drawables 
removed unnecessary field assignment 
Removed unnecessary import . 
getFileName ( ) should return the provided filename instead of a constant one 
Fix layer drawable inflation 
commit check 
Fix typo 
fixed TestMusicPlayer to corectly initialize audioContext 
record missing metric 
Prefer Integer . valueOf over explicit boxing 
commit transaction after indexing . 
Fixed the fade color initialization 
Fix typo 
IDEA - 84892 File annotations do not update on git commit 
Fix YAML Language display name 
invoke connection . close method to close es connection 
Do not return subscriber connection to prevent getting events 
which will give us a reference to the Object , that ' s probably not what we want 
Organize import . 
added @ Deprecated annotation to deprecated methods . 
add default ctor to Lexer 
Fix missing activate boolean 
help ID ( PY - 4114 ) 
Make TranslucentConversionListener a SystemApi 
Make an internal class package private 
LPS - 55175 Fix SF 
Corrected method name setSelectedNavigationIndex to setSelectedNavigationItem in the exception message 
added helper method for builder implementations 
HHH - 6421 Reduce log level of LazyInitializationException from ERROR to TRACE 
Declare two fields as final in BsonBinaryReader . Mark 
between works only with numbers , should also support dates 
clock skew detection needs to be closable , it doesn ' t fix itself 
added PLoggerFactory . unregister ( ) 
Add Protocol . BASE_ETHERNET 
return the correct format for Instruction35s 
Fix some test failures 
Call setExtent ( ) when setWorld ( ) is caleld on ParserContext . 
added constructor that takes the parent class loader 
Make git status command silent 
Drop unused private member mIgnoreGutter in ViewPager 
enable copy reference in modal context ( IDEA - 13942 ) 
Fix Spinner not restoring selection when set to GONE 
Throw an exception if unsupported verb is used 
turn off indeterminate progress thing on sign out 
Updated version in Mongo class 
IDEA - 53534 Fix wrong configurable selection on settings reopen 
Increased number of items for render from 5 to 10 
removed warning 
Fix bug with adding search source . 
Fix build due to added API 
update OK button 
Remove unnecessary import in DisplayUtils 
undo a change 
Renamed " parent " to " endSubTable " method . 
set filename 
remove unused field 
added release notes for 3 . 2 . 2 patch 
CompositeShader , add unimplemented method to fix warning 
remove spurious import 
Updated schema version 
Remove unused import . 
Fix the build when ViewDebug . TRACE_RECYCLER is set to true . 
change result type to long ( copy & paste error ) 
Set activity state correctly when ending activity . 
Add missing R file change . 
Fix constructor error introduced in last checkin 
Remove unused import in Scheduler . java 
Remove unnecessary rule key inclusion . 
Adding missing break statement in VideoCallProvider . 
Fix reading sleep policy 
Removed unused import in Format class 
Do not expose WifiManager . isNanSupported as new API 
Fix compile error 
remove unhelpful System . out . println 
Removed close ( ) override that did nothing and did not call super . close ( ) 
Set max pool size before core to avoid IAE by OpenJDK implementation . 
exclude incompatible test case 
removed non - functional history tree provider 
Revert " marked class as abstract " 
removed spurious System . out . println ( ) 
Fix transaction ( ) returning null 
Remove dead store to environmentConfig . 
Remove unused import . 
Updated version 
Fix LayoutInflater copy constructor logic . 
Add a class PlainSaslServer that implements the SaslServer interface - - fix the method name from setup to before 
Remove auto - LF conversion from . 
Fix source formatter 
fixed javadoc 
Deprecate also implementation method 
Fix typo . 
Fix deselction of all gpx 
Fixed formatting of data structure test code 
Fix issue with ForwardingEjbClientConfiguration 
Fix rare segfault with proper size ( ) and check for null ids 
Removed spurious log about blinking cursor 
ignore this for now 
Add getBytes to InputStream , URL and File ( patch thanks to jeremi Joslin ) 
prune empty directories when switching to just created tag or branch 
fixed NPE 
restored @ Test annotation in SimpleValidateQueryTests 
Lowering recon batch size from 7 to 3 to avoid timeout problem . 
Remove redundant static modifier 
Added missing " final " keyword 
data type convert error . 
Fix an erroneous import 
Allow null filenamePattern in RequestLogConfiguration 
Restored public access for Entities . EscapeMode 
Removes an empty line 
Remove obsolete comment 
Have output for valid configuration . 
Delegate exclude mimetypes to FasttrackBadgeWidget 
Added missing @ Override annotation in QueryCacheRecord . 
Don ' t change keyboard state in setIconifiedByDefault . 
Fix typo 
Investigating BZ 59261 
Actually return the registry entry , not null . 
Fix build break 
Revert r . 831830 . 
remove unusage service type . 
Fix checkstyle 
fixed issue with implementation of getFiles in UsageTarget 
